services:
  
  api:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"    
    depends_on:      
      - mongodb
    volumes:
      - .:/app
    entrypoint: ["/app/start.sh"]   
    
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:


